### ISSUE TITLE
Where is helper_functions ?

### ISSUE THREAD

**Issue by Uzumaki-C** [MrGiovanni/UNetPlusPlus#18]
import helper_functions as H
...
IoU = H.compute_iou(y_test, p_test)
print(">> Testing dataset mIoU  = {:.2f}%".format(np.mean(IoU)))

**Comment by MrGiovanni** [comment]
Thanks for letting me know the missing file. 
I have updated the script "BRATS2013_application.py" 
by removing the line "import helper_functions as H" because the function "compute_iou" has been defined in "model_logic.py". 
You may load it directly through "from model_logic import *".

Best regards,
Zongwei
